name: Test de Actions 2
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
